jobs:
  Test:
    name: Run tests
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/cache@v2
      with:
        key: maven-java-${{ matrix.jdk }}
        path: ~/.m2/repository
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Install JDK
      uses: joschi/setup-jdk@v2
      with:
        java-version: ${{ matrix.jdk }}
    - continue-on-error: true
      name: Run tests
      run: mvn -q clean verify -B
    strategy:
      matrix:
        include:
        - jdk: 21
          os: ubuntu-latest
        jdk:
        - 8
        os:
        - ubuntu-latest
        - windows-latest
name: CI
on:
  repository_dispatch:
    types: trigger-ga___ci.yml
